### ISSUE TITLE
Crashes on savegame load

### ISSUE THREAD

**Issue by therock182** [deniszholob/factorio-mod-evolution-indicator#1]
With existing savegame this mod crashes:

The mod DDD Evolution Indicator (0.0.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event ddd-evolution-indicator::on_tick (ID 0)
ddd-evolution-indicator/modules/evolution.lua:164: attempt to index a nil value
stack traceback:
ddd-evolution-indicator/modules/evolution.lua:164: in function 'update_evolution'
ddd-evolution-indicator/modules/evolution.lua:75: in function 'handler'
stdlib/stdlib/event/event.lua:342: in function 'pcall'
stdlib/stdlib/event/event.lua:362: in function 'dispatch_event'
stdlib/stdlib/event/event.lua:438: in function <stdlib/stdlib/event/event.lua:396>

[factorio-previous.log](https://github.com/deniszholob/factorio-mod-evolution-indicator/files/9085011/factorio-previous.log)

**Comment by deniszholob** [comment]
Thanks for the bug report @therock182 !
Ill take a look/try and replicate it

**Comment by deniszholob** [comment]
@therock182 I could not replicate on my end, trying some different save files
I suspect some name conflict with one of your other mods, so I added a prefix to mine, let me know if you still get errors in the update (v0.0.3)

**Comment by therock182** [comment]
i disabled all my mods except yours. trying to load your mod with my old savegame the game crashed as before.
with a fresh savegame it works. 

[factorio-current.log](https://github.com/deniszholob/factorio-mod-evolution-indicator/files/9087975/factorio-current.log)

here is my savegame, if you want some more testing and it helps you.

https://easyupload.io/phto20


thanks for your trying to help me, for me it would be ok to close this issue now.

**Comment by deniszholob** [comment]
Thanks for the save file
I suppose its the old save game that is breaking it if it works with a new one, ill fiddle with it next week
